---
- name: Vagrant provisioning using Ansible Playbook for centos 7.x
  hosts: all
  vars:
    ENV: "ENV=php-fpm"
    server_hostname: www.amihuradocker.tk
  tasks:
    - name: install packages
      yum: name={{ item }} state=latest update_cache=yes
      with_items:
        - git
        - wget
        - curl

    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh
      args:
        creates: /usr/bin/docker

    # required to install docker-py
    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python
      args:
        creates: /usr/local/bin/pip

    # required by ansible docker module
    - name: install docker-py
      pip: name=docker-py version=1.1.0 # v1.1.0 is workaround from https://github.com/ansible/ansible/issues/10879#issuecomment-97738264

    - name: Start docker daemon
      service: name=docker state=started enabled=yes

    - name: Deploy site files from Github repository
      git: repo=https://github.com/amihura/ansible-docker-lemp.git dest=/opt/ansible-docker-lemp update=yes force=yes

    - name: Changing localhost in nginx conf
      command: sed -i 's/localhost/{{ server_hostname }}/g' /opt/ansible-docker-lemp/docker/nginx/php-fpm.conf

    - name: add masqrd to proftpd conf
      lineinfile: dest=/opt/ansible-docker-lemp/docker/proftpd/proftpd.conf
                  regexp="MasqueradeAddress {{ server_hostname }}"
                  line="MasqueradeAddress {{ server_hostname }}"

    - name: check or build mysql image
      docker_image:
        path: /opt/ansible-docker-lemp/docker/mysql
        name: mysql-img
        state: present

    - name: mysql container
      docker:
        image: mysql-img
        name: mysql
        state: reloaded

    - name: check or build php-fpm image
      docker_image:
        path: /opt/ansible-docker-lemp/docker/php-fpm
        name: php-fpm-img
        state: present

    - name: php-fpm container
      docker:
        image: php-fpm-img
        name: php-fpm
        state: reloaded
        links:
        - "mysql:mysql"
        volumes_from:
        - mysql
        env: "{{ ENV }}"

    - name: check or build nginx image
      docker_image:
        path: /opt/ansible-docker-lemp/docker/nginx
        name: nginx-img
        state: present

    - name: nginx container
      docker:
        image: nginx-img
        name: nginx
        state: reloaded
        volumes_from:
          - "php-fpm"
        links:
          - "php-fpm:php-fpm"
        ports:
          - "80:80"
          - "443:443"
        env: "{{ ENV }}"

    - name: check or build proftpd image
      docker_image:
        path: /opt/ansible-docker-lemp/docker/proftpd
        name: proftpd-img
        state: present

    - name: proftpd container
      docker:
        image: proftpd-img
        name: proftpd
        state: reloaded
        net: host
        volumes_from:
          - "php-fpm"
